### ISSUE TITLE
V1.5 doe not run in macOS M2 with Sequoia

### ISSUE THREAD

**Issue by TresPorCiento** [UltiNaruto/VitaPadClient-java#2]
this happens when I download V1.5

Caused by: java.lang.SecurityException: Prohibited package name: java.sql

Any idea?

**Comment by UltiNaruto** [comment]
The project is quite old. Probably happens because it uses a very old java version. I'll try to update it when I get back home.

EDIT: It uses JDK 8. I'll recompile it to latest.

**Comment by UltiNaruto** [comment]
Could you test version 1.6? Make sure to be on JDK 23 at least.

**Comment by TresPorCiento** [comment]
Downloads % java -version
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment Zulu23.30+13-CA (build 23.0.1+11)
OpenJDK 64-Bit Server VM Zulu23.30+13-CA (build 23.0.1+11, mixed mode, sharing)
Downloads %  
Downloads % java -jar VitaPadClient-3.jar
VitaPad Client by UltiNaruto
Heavily based on Rinnegatamente version

Insert Vita IP: 192.168.68.73

IP: 192.168.68.73
Port: 5000


Client socket created on port 5000
Connection established!java.lang.NullPointerException: Cannot read field "buttons" because "padPacket" is null
	at psp2.UltiNaruto.VitaPadClient.Main.isButtonPressed(Main.java:147)
	at psp2.UltiNaruto.VitaPadClient.Main.Start(Main.java:343)
	at com.wrapper.WrapperMain.WrapperMain.main(WrapperMain.java:88)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:63)
